# -*- coding: utf-8 -*-
"""Clase_8_8_SEPTIEMBRE 2022

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tTCJANbfDpJhR9IeW-87_CIeU9O7AGuv
"""



"""<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTANDO A: ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR: DAVID MANOSALVA**
#**GRADO DECIMO**
#**8 DE SEPTIEMBRE DE 2022**

#**¿QUE ES PYTHON?**
#Python es un lenguaje de programación de alto nivel que se utiliza para desarrollar aplicaciones de todo tipo. A diferencia de otros lenguajes como Java o .NET, se trata de un lenguaje interpretado, es decir, que no es necesario compilarlo para ejecutar las aplicaciones escritas en Python, sino que se ejecutan directamente por el ordenador utilizando un programa denominado interpretador, por lo que no es necesario “traducirlo” a lenguaje máquina. 

#FECHA DE LANSAMIENTO:
#Guido Van Rossum publicó la primera versión del código Python (versión 0.9.0) en 1991.
#CREADORES:
#Python fue creado por Guido van Rossum,

#RECUPERADO DE:
https://www.becas-santander.com/es/blog/python-que-es.html https://aws.amazon.com/es/what-is/python/ https://www.redalyc.org/pdf/1815/181531232001.pdf
"""

print("Esto es una suma")
numero_uno = 45
numero_dos = 5
resultado = numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno = 70
numero_dos = 2
resultado = numero_uno - numero_dos
print(resultado)

print("Esto es una multiplicacion")
numero_uno = 9
numero_dos = 3
resultado = numero_uno * numero_dos
print(resultado)

print("Esto es una division")
numero_uno = 63
numero_dos = 3
resultado = numero_uno / numero_dos
print(resultado)

"""#Ejercicios de Tipos de Datos Simples

##Ejercicio 1
Escribir un programa que pregunte el nombre del usuario en la consola y un numero entero e imprima por pantalla en las lineas distintas el nombr del ususario tantas veces como el numero introducido
"""

nombre = input("¿Como te llamas?")
n = input("Introduce tu numero entero: ")
print((nombre + "\n") * int (n))



"""##Ejercicio 2

escribir un programa que pida al usuario su peso (en kg) y estatura (en metros),calcule el indice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'tu indece de masa corporal es <imc> 'donde <imc> es el indice de masa corporal calculado redondeado con dos decimales



"""

peso = input("¿cual es tu peso en kg?")
estatura = input("¿cual es tu estatura en metros")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu indice de masa corporal es " + str(imc))

"""# **Librerias en Phyton**

Las librerías de Python responden al conjunto de implementaciones que permiten codificar este lenguaje, con el objeto de crear una interfaz independiente.
"""